name: Run ktlint with reviewdog
on: [pull_request]
jobs: 
  ktlint:
    name: Check Code Quality
    runs-on: ubuntu-latest
    
    steps:
      - name: Clone repo
        uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: ktlint
        uses: ScaCap/action-ktlint@master
        with:
          github_token: ${{ secrets.access_token }}
          reporter: github-pr-check
          level: warning
          filter_mode: added
          android: true
